name: Create release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest

    # This permission is required to create a release and upload assets.
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10
          run_install: false
      - name: Set-up Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - name: Update package.json version from tag
        run: |
          # Strip the 'v' prefix from the tag name to get a semantic version.
          VERSION=${{ github.ref_name }}
          npm version --no-git-tag-version --allow-same-version "${VERSION#v}"

      - name: Install dependencies
        run: npm ci

      - name: Build card
        run: npm run build
      - name: Lint card
        run: npm run lint
      - name: Test
        run: npm test
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v6
        with:
          configurationJson: |
            {
              "categories": [
                {
                  "title": "## 🚀 Features",
                  "labels": ["🌟 feature", "✨ feature-request", "enhancement", "request"]
                },
                {
                  "title": "## 🛠 Fixes",
                  "labels": ["fix", "🐛 bug"]
                },
                {
                  "title": "## 🧩 Dependencies",
                  "labels": ["dependencies"]
                },
                {
                  "title": "## ⚙️ Configuration",
                  "labels": ["configuration"]
                },
                {
                  "title": "## 📝 Documentation",
                  "labels": ["📝 documentation"]
                },
                {
                  "title": "## 📦 Other",
                  "labels": []
                }
              ],
              "template": "#{{CHANGELOG}}",
              "pr_template": "- #{{TITLE}}\n   - PR: ##{{NUMBER}} by @#{{AUTHOR}}",
              "empty_template": "#{{OWNER}}\n#{{REPO}}\n#{{FROM_TAG}}\n#{{TO_TAG}}",
              "max_pull_requests": 1000,
              "max_back_track_time_days": 1000
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            dist/blitzortung-lightning-card.js
          draft: true
          body: |
            ${{ steps.build_changelog.outputs.changelog }}
